### ISSUE TITLE
gettext and glib point to libc.so instead of libc.so.6

### ISSUE THREAD

**Issue by bramtayl** [JuliaPackaging/Yggdrasil#2444] opened 2021-01-25 14:23 UTC
I'm getting this error:

gettext: error while loading shared libraries: libc.so: cannot open shared object file: No such file or directory

**Comment by giordano** [comment] 2021-01-26 19:12
What platform is this?

**Comment by bramtayl** [comment] 2021-01-27 17:23
Whichever the default first one is? So Linux(:x86_64, libc=:glibc) I guess. I haven't tried it on any of the others. I'm running ubuntu.

**Comment by giordano** [comment] 2021-01-27 17:30
If you want help you should really provide something to reproduce the issue.  It isn't much fun for me to keep asking questions to get some information :slightly_smiling_face:  Also, I'm not really convinced the build system should run programs for the target.  If it needs gettext, it should use the one from the system

**Comment by bramtayl** [comment] 2021-01-27 18:09
Ok, sorry. Thanks for the help! Is this enough information?

```
julia> run_wizard()
Would you like to resume the previous incomplete wizard run?
   Resume previous run
 > Start from scratch

    o      `.
   o*o      \'-_               00000000: 01111111  .
     \\      \;"".     ,;.--*  00000001: 01000101  E
      \\     ,\''--.--'/       00000002: 01001100  L
      :=\--<' `""  _   |       00000003: 01000110  F
      ||\\     `" / ''--       00000004: 00000010  .
      `/_\\,-|    |            00000005: 00000001  .
          \\/     L
           \\ ,'   \
         _/ L'   `  \          Join us in the #binarybuilder channel on the
        /  /    /   /          community slack: https://julialang.slack.com
       /  /    |    \
      "_''--_-''---__=;        https://github.com/JuliaPackaging/BinaryBuilder.jl

Welcome to the BinaryBuilder wizard.  We'll get you set up in no time.

			# Step 1: Select your platforms

Make a platform selection
 > All Supported Platforms
   Select by Operating System
   Fully Custom Platform Choice


			# Step 2a: Obtain the source code

Please enter a URL (git repository or compressed archive) containing the source code to build:
> https://github.com/jackaudio/jack2/archive/v1.9.17.tar.gz

[13:06:23] ######################################################################## 100.0%##O=#  #                [13:06:24]       #=O=#   #     #                                                         

Would you like to download additional sources?  [y/N]: n

			# Step 2b: Obtain binary dependencies (if any)

Do you require any (binary) dependencies?  [y/N]: y
Enter JLL package name:
> Gettext

   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
Would you like to provide additional dependencies?  [y/N]: n

Enter a name for this project.  This will be used for filenames:
> Jack2

Enter a version number for this project:
> 1.9.17

Do you want to customize the set of compilers? [y/N]: n
			# Step 3: Build for Linux(:x86_64, libc=:glibc)

You will now be dropped into the cross-compilation environment.
Please compile the package. Your initial compilation target is x86_64-linux-gnu
The $prefix environment variable contains the target directory.
Once you are done, exit by typing `exit` or `^D`

   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Updating `/tmp/jl_ifVXmJ/5sKDgTAT/.project/Project.toml`
  [78b55507] + Gettext_jll v0.20.1+7
Updating `/tmp/jl_ifVXmJ/5sKDgTAT/.project/Manifest.toml`
  [56f22d72] + Artifacts v1.3.0
  [78b55507] + Gettext_jll v0.20.1+7
  [692b3bcd] + JLLWrappers v1.2.0
  [94ce4f54] + Libiconv_jll v1.16.0+7
  [02c8fc9c] + XML2_jll v2.9.10+3
  [83775a58] + Zlib_jll v1.2.11+18
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
You have the following contents in your working directory:
  - jack2-1.9.17

sandbox:${WORKSPACE}/srcdir # gettext --help
gettext: error while loading shared libraries: libc.so: cannot open shared object file: No such file or directory
```

> Also, I'm not really convinced the build system should run programs for the target. If it needs gettext, it should use the one from the system

I'm not sure I understand this...how would I get binarybuilder to detect the gettext that exists in the system?

**Comment by giordano** [comment] 2021-01-27 18:13
> I'm not sure I understand this...how would I get binarybuilder to detect the gettext that exists in the system?

https://docs.binarybuilder.org/stable/FAQ/#Can-I-install-packages-in-the-build-environment?-1

**Comment by bramtayl** [comment] 2021-01-28 00:05
Ok, well I knew that you could use `apk` to add packages, but the docs make it sound discouraged? Also, meson seems to be able to find packages installed as `jll`s but not with `apk`... do I need to tell meson where to look for the apk packages or something?

**Comment by giordano** [comment] 2021-01-28 00:10
> Ok, well I knew that you could use apk to add packages, but the docs make it sound discouraged?

It literally says

> The package manager is useful only to install utilities, tools or libraries that are needed exclusively at compile time on the build system.

which is _exactly_ your case.  How is this discouraged?

> Also, meson seems to be able to find packages installed as jlls but not with apk...

How does it help finding a tool for the target if you need a tool for the host?

**Comment by bramtayl** [comment] 2021-01-28 02:50
I guess I just misread the docs. I don't really understand the last part about tools for the target and host though?

**Comment by giordano** [comment] 2021-01-28 03:06
"target" = platform for which we're building
"host" = platform where we're building

The building environment can only run executables for the host platform, and exceptionally a couple of other platforms, but it isn't relevant: in general assume you can't run executables for the target. It doesn't make sense to run executables built for the target, since they are meant for a foreign platform. If you need to run something, it must be something for the host

**Comment by bramtayl** [comment] 2021-01-28 03:50
Ok, so... `apk add gettext` will download a binary built for the host platform and including `Gettext_jll` as a binary dependency will download a binary built for the target platform, and the build system is smart enough to know which kind of binary it's looking for?

**Comment by bramtayl** [comment] 2021-01-28 05:47
Ahaha! I've discovered that

```
ln -s /usr/lib ${WORKSPACE}/destdir/lib
ln -s /usr/include ${WORKSPACE}/destdir/include
```

seems to work so that binarybuilder can access things installed with apk. Is this what I want?

**Comment by giordano** [comment] 2021-01-28 11:58
> Is this what I want?

Absolutely no.  You _never ever_ want to mix the host environment (like stuff under `/usr`) with the target environment (like stuff `${prefix}`).  You simply have to install `gettext`, if it isn't already, with
```
apk add gettext
```
that's all.

PS: _never_ use explicit `${WORKSPACE}/destdir/lib` or `${WORKSPACE}/destdir/lib`, in future versions thos paths may even not work anymore.  Instead, _always_ use the most specific [environment variable](https://docs.binarybuilder.org/dev/build_tips/#Automatic-environment-variables), like `${libdir}` or `${includedir}`

**Comment by bramtayl** [comment] 2021-01-28 15:38
Um...I'm so sorry that I'm so helpless at this. I'm still confused though...

The gettext version that gets installled as a jll seems to be broken, and maybe not what we want anyway, but gets installed by other dependencies...so I figured out a way to purge it:

```
cd ../destdir
rm include/gettext*
rm lib/libgettext*
rm bin/gettext
apk add gettext
apk add gettext-dev
```

That seems to work fine, but now I'm having the same problem with glib:

```
Compiling gsettings schemas...
glib-compile-schemas: error while loading shared libraries: libc.so: cannot open shared object file: No such file or directory
```

And, during the meson build, glib is listed as a runtime dependency, which means if I understand correctly, it should be installed as a jll and not via apk?

**Comment by giordano** [comment] 2021-01-28 15:52
While it'd be better that binaries link to `libc.so.6` instead of `libc.so` (and I have no idea why that happens), I don't think that's totally broken, as most systems would have `libc.so` pointing to `libc.so.6`.  The real issue here is that you keep running executables for the target when you shouldn't

**Comment by bramtayl** [comment] 2021-01-28 16:32
Ok, maybe I'm starting to get it?

```
export PATH=$(echo "$PATH" | sed -e 's/:\/workspace\/destdir\/bin$//')
```

This seemed to do the trick. Since the host shouldn't run target binaries, maybe they shouldn't be in the path?

**Comment by giordano** [comment] 2021-01-28 16:39
`${bindir}` is purposefully in the `PATH`: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/b699dcdaeb099bb374b39f33580ee07e719cf6e7/src/Runner.jl#L865-L866.  Removing that directory from the `PATH` won't help anything if you don't have a replacement somewhere else before `${bindir}`, which means "somewhere else in the PATH", since `${bindir}` is the very last element of the `PATH`.  Get a tool for the host, it'll be run before anything in `${bindir}`, as simple as that

**Comment by bramtayl** [comment] 2021-01-28 18:14
Ok, got it! It turns out changing the path wasn't what helped but the `hash -r` afterwards, which still seems to be necessary.

**Comment by giordano** [comment] 2021-01-28 18:39
Rehashing isn't needed if you do the right thing from the beginning :slightly_smiling_face:

**Comment by giordano** [comment] 2021-05-20 00:19
I still have no idea what's the issue: since all libraries I could see in [`Glib_jll`](https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.59.0%2B2/Glib.v2.59.0.x86_64-linux-gnu.tar.gz) and [`Gettext_jll`](https://github.com/JuliaBinaryWrappers/Gettext_jll.jl/releases/download/Gettext-v0.20.1%2B5/Gettext.v0.20.1.x86_64-linux-gnu.tar.gz) require `libc.so.6` (you can verify for example with `readelf -d *.so|grep libc`) I'm going to close this ticket as it isn't an issue.

**Closed by giordano** 2021-05-20 00:19 UTC
