### ISSUE TITLE
Git_jll doesn't work with HTTP remotes?

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPackaging/Yggdrasil#452] opened 2020-01-31 19:08 UTC
```julia
git() do git
           readlines(`$git ls-remote http://github.com/JuliaPlots/MakieReferenceImages`)
       end
fatal: unable to find remote helper for 'http'
ERROR: failed process: Process(`/Users/anshul/.julia/artifacts/4c5e6fa65bda6837ba17cf2e58e0016f6229e211/bin/git ls-remote http://github.com/JuliaPlots/MakieReferenceImages`, ProcessExited(128)) [128]
```

This works on my local, command-line git just fine.

**Comment by giordano** [comment] 2020-01-31 19:13
Duplicate of #284

**Closed by giordano** 2020-01-31 19:13 UTC
