### ISSUE TITLE
Graphviz_jll not working?

### ISSUE THREAD

**Issue by tkf** [JuliaPackaging/Yggdrasil#3757] opened 2021-10-16 23:05 UTC
In a `dot` CLI installed in Ubuntu, I get

```
shell> cat hello.dot
digraph G {Hello->World}

shell> dot -Tpng hello.dot -ohello.png

shell> dot -T?
Format: "?" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gd gd2 gif gv imap imap_np ismap jpe
jpeg jpg json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz vrml wbmp x11 xdot xdot1.2 xdot1.4 xdot_j
son xlib
```

However, with `Graphviz_jll.dot`, I get

```
julia> import Graphviz_jll

julia> Graphviz_jll.dot() do cmd
           run(`$cmd -Tpng hello.dot -ohello.png`)
       end
Format: "png" not recognized. Use one of:
ERROR: failed process: Process(`/home/arakaki/.julia/artifacts/edb465e7f0fe4ebd11efbafb9df31084e544ac07/bin/dot -Tpng hello.
dot -ohello.png`, ProcessExited(1)) [1]
...

julia> Graphviz_jll.dot() do cmd
           run(`$cmd "-T?"`)
       end
Format: "?" not recognized. Use one of:
ERROR: failed process: Process(`/home/arakaki/.julia/artifacts/edb465e7f0fe4ebd11efbafb9df31084e544ac07/bin/dot '-T?'`, ProcessExited(1)) [1]
...
```

Some possibly-relevant info:

```
(@v1.6) pkg> st Graphviz_jll
      Status `~/.julia/environments/v1.6/Project.toml`
  [3c863552] Graphviz_jll v2.42.3+1

julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7502 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

**Comment by giordano** [comment] 2021-10-16 23:11
Duplicate of #1428

**Closed by giordano** 2021-10-16 23:11 UTC
