### ISSUE TITLE
Cannot instantiate env in Julia 1.10, "ERROR: Unable to automatically download/install artifact 'adwaita_icon_theme'"

### ISSUE THREAD

**Issue by revolutionflourlake772** [JuliaPackaging/Yggdrasil#7860] opened 2023-12-27 16:49 UTC
Hello, it seems a generic stdlib artifact cannot be downloaded when instantiating an environment in Julia 1.10 (Windows 10, Intel). Here's my REPL output:

      Downloaded artifact: adwaita_icon_theme
      Downloaded artifact: adwaita_icon_theme
    ERROR: Unable to automatically download/install artifact 'adwaita_icon_theme' from sources listed in 'C:\1\.julia\packages\adwaita_icon_theme_jll\YjPmX\Artifacts.toml'.
    Sources attempted:
    - https://pkg.julialang.org/artifact/65eca7c48dea1e32203b205613441ce9506045b4
        Error: Tree Hash Mismatch!
      Expected git-tree-sha1:   65eca7c48dea1e32203b205613441ce9506045b4
      Calculated git-tree-sha1: 043d0732f572e66059278f5964e3752f018a5cdf
    - https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/releases/download/adwaita_icon_theme-v3.33.92+4/adwaita_icon_theme.v3.33.92.any.tar.gz
        Error: Tree Hash Mismatch!
      Expected git-tree-sha1:   65eca7c48dea1e32203b205613441ce9506045b4
      Calculated git-tree-sha1: 043d0732f572e66059278f5964e3752f018a5cdf
    
    Stacktrace:
      [1] error(s::String)
        @ Base .\error.jl:35
      [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, io::Base.TTY)
        @ Pkg.Artifacts C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\Artifacts.jl:422
      [3] download_artifacts(env::Pkg.Types.EnvCache; platform::Base.BinaryPlatforms.Platform, julia_version::VersionNumber, verbose::Bool, io::Base.TTY)
        @ Pkg.Operations C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:755
      [4] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, level::Pkg.Types.UpgradeLevel; skip_writing_project::Bool, preserve::Nothing)
        @ Pkg.Operations C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:1542
      [5] up
        @ Pkg.Operations C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:1519 [inlined]
      [6] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; level::Pkg.Types.UpgradeLevel, mode::Pkg.Types.PackageMode, preserve::Nothing, update_registry::Bool, skip_writing_project::Bool, kwargs::@Kwargs{io::Base.TTY})
        @ Pkg.API C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\API.jl:351
      [7] up(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{})
        @ Pkg.API C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\API.jl:159
      [8] up(pkgs::Vector{Pkg.Types.PackageSpec})
        @ Pkg.API C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\API.jl:148
      [9] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
        @ Pkg.REPLMode C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\REPLMode\REPLMode.jl:412
     [10] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
        @ Pkg.REPLMode C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\REPLMode\REPLMode.jl:390
     [11] do_cmd
        @ Pkg.REPLMode C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\REPLMode\REPLMode.jl:380 [inlined]
     [12] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
        @ Pkg.REPLMode C:\1\JL1X\share\julia\stdlib\v1.10\Pkg\src\REPLMode\REPLMode.jl:557
     [13] #invokelatest#2
        @ Base .\essentials.jl:887 [inlined]
     [14] invokelatest
        @ Base .\essentials.jl:884 [inlined]
     [15] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
        @ REPL.LineEdit C:\1\JL1X\share\julia\stdlib\v1.10\REPL\src\LineEdit.jl:2656
     [16] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
        @ REPL C:\1\JL1X\share\julia\stdlib\v1.10\REPL\src\REPL.jl:1312
     [17] (::REPL.var"#62#68"{REPL.LineEditREPL, REPL.REPLBackendRef})()
        @ REPL C:\1\JL1X\share\julia\stdlib\v1.10\REPL\src\REPL.jl:386
    
    (JL1XVENV) pkg>

The tarball SHA 256 hash that I get matches what's in the auto-generated \adwaita_icon_theme_jll\YjPmX\Artifacts.toml file.

I have no idea why the calculated git tree SHA1 hash (043d0732f572e66059278f5964e3752f018a5cdf) is different from what's in the 3.33.92+4 hash ([adwaita_icon_theme] git-tree-sha1 = "65eca7c48dea1e32203b205613441ce9506045b4", https://github.com/JuliaBinaryWrappers/adwaita_icon_theme_jll.jl/compare/adwaita_icon_theme-v3.33.92+4...master). The subsequent version of adwaita_icon_theme_jll (adwaita_icon_theme-v43.0.0+0) also has a different hash than the current calculated one (as do the prior versions): git-tree-sha1 = "6012e83a109fbe39e539578e2f4275762505f458".

As this is all autogenerated, and is preventing me from using Julia 1.10 on windows currently; I presume it is appropriate to submit here as it seems like a substantive issue.

It seems some step of the compression / download / extraction / hash calculation process for the git tree has altered it somewhere, hence causing the issue.

**Comment by giordano** [comment] 2023-12-27 17:02
Sounds like a duplicate of https://github.com/JuliaLang/Pkg.jl/issues/3643, likely nothing we can do about it here if it's a Pkg bug.

**Comment by revolutionflourlake772** [comment] 2023-12-27 17:22
Yeah, makes more sense that it is a Pkg issue, thanks for pointing that out. I commented there, including that I'm getting an identical type of error for iso_codes_jll now. Thanks for linking this to that issue.

**Comment by giordano** [comment] 2023-12-31 09:20
I'm closing this ticket as the issue is already tracked upstream in Pkg repository, there's no value in keeping this one open, we can't do anything about it here.

**Closed by giordano** 2023-12-31 09:20 UTC
