### ISSUE TITLE
Build Stan

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#2359] opened 2021-01-05 20:38 UTC
Appears to be straightforward to build.

Will get used by https://github.com/StanJulia/Stan.jl

**Comment by Wimmerer** [comment] 2021-04-12 23:20
Did you want CmdStan, the C++ lib (Stan) or both?

**Comment by giordano** [comment] 2021-04-13 17:44
BTW, this is a duplicate of #1023 which has also more details, I'm going to close this in favour of the other ticket

**Closed by giordano** 2021-04-13 17:44 UTC
Labels: builder request :pray:
