### ISSUE TITLE
Artifact files are getting installed with bad owners/permissions

### ISSUE THREAD

**Issue by ViralBShah** [JuliaPackaging/Yggdrasil#1969] opened 2020-10-22 15:21 UTC
I installed GR#master, which brings in all the QT dependencies. Then I tried to wipe my `~/.julia` and got this error. I had to use `sudo` to delete. This is on a mac.

```
julia> 
➜  julia git:(master) cd
➜  ~ rm -fr .julia
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/Resources/QtMultimediaQuick.prl: Permission denied
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/Resources/Info.plist: Permission denied
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/Resources: Permission denied
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/QtMultimediaQuick: Permission denied
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/Headers/qtmultimediaquickversion.h: Permission denied
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuickVersion: Permission denied
rm: .julia/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuick: Permission denied
...
```

cc @barche

**Comment by barche** [comment] 2020-10-23 07:09
Yes, I have seen this too, but not just with Qt, e.g:

`clean_julia_depot/artifacts/7e9b46cb67072873f8c080d0a876088f757ebe84/lib/icu/67.1/Makefile.inc: Permission denied`

#NotMyBug 😉 (I think)

**Comment by ViralBShah** [comment] 2020-10-23 12:42
@giordano @staticfloat Do you know what might be going on?

**Comment by giordano** [comment] 2020-10-23 13:00
We don't modify the permissions, as far as I know, so these files with nasty permissions come straight from the build system.

**Comment by ViralBShah** [comment] 2020-10-23 13:10
That's what I thought. Perhaps something we should check when we build the bundle, and maybe even change the permissions to something reasonable?

**Comment by giordano** [comment] 2020-10-23 13:41
Minimally sanitising the permissions (at least giving write permission to the user?) might be a good idea.

**Comment by staticfloat** [comment] 2020-10-23 17:25
Julia 1.6+ already correctly deletes this.  If you run into this error on Julia 1.5 then run `pkg> gc --all` on Julia 1.6+ it should delete it for you as well.

**Comment by ViralBShah** [comment] 2020-10-23 18:16
That's nice to know.

I often do `rm -fr ~/.julia` which is where I ran into this. I like to do that fairly frequently to test things out. Given that we install in the user's home directory, it should be possible to cleanly delete the whole `.julia` directory without requiring additional permissions.

**Comment by staticfloat** [comment] 2020-10-23 18:44
The issue is that processes can strip the writable permission bit for the current user on a directory, then when you try to `rm -rf` the directory, it is unable to remove its children.  I don't see how we can prevent programs from doing that.

In this case, the program doing it is the tar extraction because the tar file requests it.  There are legitimate cases where we want strange permissions on directories (very occasionally programs will refuse to run if their directories don't have the precise permissions they want; think of how picky `ssh` is about `~/.ssh`).  I'm uncomfortable categorically denying all artifacts the ability to express these strange permissions.  The compiler shards in BB are one such case where the compilers and rootfs generate very strange permissions and need them that way.

**Comment by giordano** [comment] 2020-10-23 19:41
> I like to do that fairly frequently to test things out.

I recently discovered we have `]activate --temp` to activate a throw-away environment, that's quite convenient.

**Comment by giordano** [comment] 2020-10-31 20:59
For the specific case of ICU, I'm 99.99% sure that the files `lib/icu/X.Y/*.inc` aren't needed at runtime (Debian doesn't have them in the [runtime lib package](https://packages.debian.org/sid/amd64/libicu67/filelist), for example), so I wonder if we can just remove them.  However I don't know whether they may be needed to build libraries against ICU...

**Comment by barche** [comment] 2020-10-31 23:41
I just did a local build for ICU, none of these files have strange permissions after make install, so I have no idea why they would give problems.

**Comment by giordano** [comment] 2020-10-31 23:50
The borked files are those in `lib/icu/67.1/` as I wrote above:
```
% ls -l lib/icu/67.1 
total 16
-r--r--r-- 1 mose mose 9843 Oct 31 23:44 Makefile.inc
-r--r--r-- 1 mose mose  666 Oct 31 23:44 pkgdata.inc
% rm -f lib/icu/67.1/Makefile.inc
rm: cannot remove 'lib/icu/67.1/Makefile.inc': Permission denied
% chmod -R u+w lib/icu/67.1     
% rm -f lib/icu/67.1/Makefile.inc
```
No idea why they're don't have the write bit set for the user.

**Comment by giordano** [comment] 2020-10-31 23:53
More precisely, I think the problem is that the directory isn't writable by the user:
```
% ls -l lib/icu
total 4
dr-xr-xr-x 2 mose mose 4096 Oct 31 23:52 67.1
lrwxrwxrwx 1 mose mose    4 Oct 31 23:52 current -> 67.1
lrwxrwxrwx 1 mose mose   20 Oct 31 23:52 Makefile.inc -> current/Makefile.inc
lrwxrwxrwx 1 mose mose   19 Oct 31 23:52 pkgdata.inc -> current/pkgdata.inc
```

**Comment by barche** [comment] 2020-11-01 00:12
Is that on the unpacked tarball? Because after building I see this:

```
sandbox:${WORKSPACE}/srcdir/icu/source # ls -l $prefix/lib/icu/
total 4
drwxr-xr-x    2 root     root          4096 Oct 31 23:01 67.1
lrwxrwxrwx    1 root     root            20 Oct 31 23:01 Makefile.inc -> current/Makefile.inc
lrwxrwxrwx    1 root     root             4 Oct 31 23:01 current -> 67.1
lrwxrwxrwx    1 root     root            19 Oct 31 23:01 pkgdata.inc -> current/pkgdata.inc
```

**Comment by giordano** [comment] 2020-11-01 00:13
That was the artifact, yes

**Comment by giordano** [comment] 2020-11-01 00:34
Ok, I suspect there is a bug in the packaging function.  I commented out the lines https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/f7110cef28de9525e22677a866952b5b12a6adfe/src/AutoBuild.jl#L816-L819 so that the build directory isn't removed, and after the build I have
```
$ ls -l build/x86_64-linux-gnu/N35kby2w/destdir/lib/icu/
total 4
drwxr-xr-x 2 mose mose 4096 Nov  1 00:28 67.1
lrwxrwxrwx 1 mose mose    4 Nov  1 00:28 current -> 67.1
lrwxrwxrwx 1 mose mose   20 Nov  1 00:28 Makefile.inc -> current/Makefile.inc
lrwxrwxrwx 1 mose mose   19 Nov  1 00:28 pkgdata.inc -> current/pkgdata.inc
```
So also outside of the build environment the directory has the right permissions.

**Comment by giordano** [comment] 2020-11-01 01:02
I could track the bug down to the call to `Pkg.Artifacts.archive_artifact` at https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/79d5e733e9d7638fa8c5e7fa96d7b33934548be8/src/Prefix.jl#L176.  I don't have the time now to go deeper in `Pkg` :slightly_smiling_face:  The source directory in `~/.julia/artifacts` has the right permissions, so it looks like the tarball is being created with the wrong user bit permissions.  Since this happens with `lib/icu/67.1/` for `ICU_jll` and all `lib/Qt*/Versions/5/` directories in `Qt_jll`, I suspect numbers are problematic :thinking:

**Comment by giordano** [comment] 2020-11-01 01:32
Opened an issue for `Pkg`: https://github.com/JuliaLang/Pkg.jl/issues/2185

**Comment by devmotion** [comment] 2020-12-02 15:33
I ran into the same (?) problem with Birch_jll. The following command fails
```julia
julia> using Birch_jll

julia> mktempdir() do tmp
           cd(tmp) do
               withenv("BIRCH_PREFIX" => Birch_jll.artifact_dir) do 
                   Birch_jll.birch() do b
                       run(`$b init --package HelloWorld`)
                   end
               end
           end
       end
error: Could not open birch.yml for writing.

ERROR: failed process: Process(`/home/david/.julia/artifacts/d5cf28e8a0e038c6c8562326076bf02eab7f3743/bin/birch init --package HelloWorld`, ProcessExited(1)) [1]
```
probably due to incorrect permissions of the installed files that are then copied but can't be modified:
```julia
julia> run(`ls -la $(joinpath(Birch_jll.artifact_dir, "share", "birch"))`)
total 88
drwxr-xr-x 2 david users  4096 Dec  2 15:53 .
drwxr-xr-x 4 david users  4096 Dec  2 15:53 ..
-r--r--r-- 1 david users  2104 Dec  2 15:53 ax_check_compile_flag.m4
-r--r--r-- 1 david users  3494 Dec  2 15:53 ax_check_define.m4
-r--r--r-- 1 david users 20244 Dec  2 15:53 ax_cxx_compile_stdcxx.m4
-r--r--r-- 1 david users  5862 Dec  2 15:53 ax_gcc_builtin.m4
-r--r--r-- 1 david users   269 Dec  2 15:53 birch.yml
-r--r--r-- 1 david users    55 Dec  2 15:53 bootstrap
-r--r--r-- 1 david users  3792 Dec  2 15:53 configure.ac
-r--r--r-- 1 david users   372 Dec  2 15:53 gitignore
-r--r--r-- 1 david users    79 Dec  2 15:53 hello.birch
-r--r--r-- 1 david users 11358 Dec  2 15:53 LICENSE
-r--r--r-- 1 david users  1059 Dec  2 15:53 Makefile.am
-r--r--r-- 1 david users   560 Dec  2 15:53 mkdocs.yml
-r--r--r-- 1 david users   343 Dec  2 15:53 README.md
Process(`ls -la /home/david/.julia/artifacts/d5cf28e8a0e038c6c8562326076bf02eab7f3743/share/birch`, ProcessExited(0))
```

**Comment by devmotion** [comment] 2020-12-02 15:42
Is there anything that I can do to fix this problem for Birch?

**Comment by giordano** [comment] 2020-12-02 15:46
It'd be nice to know what's the problem in the first place.  The tarballs for `Birch` seems to have the files with the right permissions:
```
% wget -q -O - https://github.com/JuliaBinaryWrappers/Birch_jll.jl/releases/download/Birch-v1.75.0%2B0/Birch.v1.75.0.x86_64-linux-gnu-cxx11.tar.gz | tar -tzvf -
-rwxr-xr-x 0/0        32107488 1970-01-01 01:00 bin/birch
-rw-r--r-- 0/0            9370 1970-01-01 01:00 logs/Birch.log.gz
-rw-r--r-- 0/0              95 1970-01-01 01:00 logs/update_linkage_birch_libboost_filesystem.so.1.71.0.log.gz
-rw-r--r-- 0/0              92 1970-01-01 01:00 logs/update_linkage_birch_libboost_system.so.1.71.0.log.gz
-rw-r--r-- 0/0              81 1970-01-01 01:00 logs/update_linkage_birch_libyaml-0.so.2.log.gz
-rw-r--r-- 0/0              75 1970-01-01 01:00 logs/update_rpath_birch_libboost_system.so.1.71.0.log.gz
-rw-r--r-- 0/0           11358 1970-01-01 01:00 share/birch/LICENSE
-rw-r--r-- 0/0            1059 1970-01-01 01:00 share/birch/Makefile.am
-rw-r--r-- 0/0             343 1970-01-01 01:00 share/birch/README.md
-rw-r--r-- 0/0            2104 1970-01-01 01:00 share/birch/ax_check_compile_flag.m4
-rw-r--r-- 0/0            3494 1970-01-01 01:00 share/birch/ax_check_define.m4
-rw-r--r-- 0/0           20244 1970-01-01 01:00 share/birch/ax_cxx_compile_stdcxx.m4
-rw-r--r-- 0/0            5862 1970-01-01 01:00 share/birch/ax_gcc_builtin.m4
-rw-r--r-- 0/0             269 1970-01-01 01:00 share/birch/birch.yml
-rw-r--r-- 0/0              55 1970-01-01 01:00 share/birch/bootstrap
-rw-r--r-- 0/0            3792 1970-01-01 01:00 share/birch/configure.ac
-rw-r--r-- 0/0             372 1970-01-01 01:00 share/birch/gitignore
-rw-r--r-- 0/0              79 1970-01-01 01:00 share/birch/hello.birch
-rw-r--r-- 0/0             560 1970-01-01 01:00 share/birch/mkdocs.yml
-rw-r--r-- 0/0           11358 1970-01-01 01:00 share/licenses/Birch/LICENSE
```

**Comment by giordano** [comment] 2020-12-02 16:08
Fredrik pointed out on Slack that artifacts are make read-only when they are installed, see https://github.com/JuliaLang/Pkg.jl/blob/cce236e1866f6fe2653a4e202bc6eca47f8ddd7a/src/Artifacts.jl#L57-L60.  I knew that artifacts are supposed to be immutable, I didn't realise this was actually enforced.  Anyway, if you want to modify something it's probably better to use a different approach (like copying the files you need somewhere else and make them writable).

**Comment by devmotion** [comment] 2020-12-02 16:29
You mean by downloading them separately? Or copying them manually from the artifact directory and then fixing the permissions?

The files are included and installed by Birch to allow users to bootstrap a Birch package with `birch init`, see e.g. https://www.birch.sh/getting-started/hello-world/. So it seems a bit weird to reimplement this functionality if it is already provided by Birch.

Or did you have something else in mind?

**Comment by devmotion** [comment] 2020-12-02 16:30
Another alternative would be to patch Birch (maybe even upstream) such that the permissions are adjusted automatically if necessary.

**Comment by giordano** [comment] 2020-12-02 16:32
> Or copying them manually from the artifact directory and then fixing the permissions?

This.  You can use for example [`Scratch.jl`](https://github.com/JuliaPackaging/Scratch.jl).

> Another alternative would be to patch Birch (maybe even upstream) such that the permissions are adjusted automatically if necessary.

Not really since that would break the assumption that artifacts are immutable.

**Comment by devmotion** [comment] 2020-12-02 16:34
> Not really since that would break the assumption that artifacts are immutable.

I didn't mean to suggest changing the permissions of the files in the artifacts, I rather thought that `birch init` should fix the file permission when the resources are copied to some user directory.

**Comment by giordano** [comment] 2020-12-02 17:08
To be clear, the error reported above is different from what you're experiencing: `ICU_jll` has wrong permissions of some files in the _tarball_, due to https://github.com/JuliaLang/Pkg.jl/issues/2185, while you're seeing that the files are made read-only when they're installed, for immutability.

**Comment by devmotion** [comment] 2020-12-02 21:17
Yes, I realized this now. My problem above should be solved by https://github.com/lawmurray/Birch/pull/8.

**Comment by ViralBShah** [comment] 2020-12-08 20:59
This is a mac only issue.

**Comment by ViralBShah** [comment] 2020-12-09 02:19
I noted in https://github.com/JuliaPackaging/Yggdrasil/pull/2231 that with the recently created `Qt_jll` package, I as a user do not have the permission to delete the files.

If Pkg installs artifacts as read-only, shouldn't this apply to all `jll` files? I can literally wipe my `.julia` without fuss when it contains dozens of other jll artifacts. I just can't wipe the stuff that `Qt_jll` installs.

**Comment by staticfloat** [comment] 2020-12-09 06:39
Are you installing with Julia 1.5 or 1.6?  I do not think this should happen on 1.6.  On 1.5, we have a workaround in `Pkg.gc()` to alter the permissions before they're attempted to be deleted.

**Comment by giordano** [comment] 2020-12-09 09:49
As far as I can see, `Pkg.set_readonly` sets as read-only only files, not directories, but I _think_ it should check whether the file is a link to a directory.

**Comment by ViralBShah** [comment] 2020-12-09 14:12
I ran into the issue on both 1.5 and 1.6. I have a problem with `rm -fr .julia` only on mac. On linux, I don't have a problem with wiping my `.julia`.

**Comment by giordano** [comment] 2020-12-09 14:15
Yes, because the behaviour of `Pkg.set_readonly` is always the same in v1.5 and v1.6, and the symlinks are only in the macOS tarball.  I have the fix for `Pkg.jl`, I need to write the tests for that

**Comment by giordano** [comment] 2021-04-08 10:23
I'm closing this ticket: the issue was due to packaging in of the tarballs with Pkg (https://github.com/JuliaLang/Pkg.jl/issues/2185), but that got fixed at some point. We can't do anything for the already existing tarballs, all new tarballs should have the files with the right permissions, nothing to do here.

**Closed by giordano** 2021-04-08 10:23 UTC
