### ISSUE TITLE
[graphite2_jll] Error installing on Julia 1.8.0

### ISSUE THREAD

**Issue by jdeldre** [JuliaPackaging/Yggdrasil#4358] opened 2022-02-02 23:37 UTC
I'm getting the following behavior when I try to `] add Graphite2_jll` with the Julia nightly build (1.8.0)

```
(@v1.8) pkg> add Graphite2_jll
   Resolving package versions...
ERROR: /var/folders/1s/lds3nd1s7xn4mgf0vxqwg0kr0000gn/T/jl_ha027GtGhvj9E3Jt
Can not open the file as archive

ERROR: Error when installing package Graphite2_jll:
failed process: Process(setenv(`/Applications/Julia-1.8.app/Contents/Resources/julia/libexec/7z x /var/folders/1s/lds3nd1s7xn4mgf0vxqwg0kr0000gn/T/jl_ha027GtGhvj9E3Jt -so`,["XPC_FLAGS=0x0", "PATH=/Applications/Julia-1.8.app/Contents/Resources/julia/libexec:/usr/local/opt/python@3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin", "PWD=/Users/jeff/JuliaProjects/ImmersedLayers", "DISPLAY=/private/tmp/com.apple.launchd.AON8FycAeg/org.macosforge.xquartz:0", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "SHELL=/bin/zsh", "DYLD_FALLBACK_LIBRARY_PATH=/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib/julia:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/../lib:/Users/jeff/lib:/usr/local/lib:/lib:/usr/lib", "__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0", "TMPDIR=/var/folders/1s/lds3nd1s7xn4mgf0vxqwg0kr0000gn/T/", "LANG=en_US.UTF-8", "JULIA_PKG_DEVDIR=/Users/jeff/JuliaProjects/", "SHLVL=1", "LOGNAME=jeff", "TERM_SESSION_ID=6EB815DF-CA73-49FB-B095-535D6084A6D2", "SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.UeimGH5fgz/Listeners", "OLDPWD=/Users/jeff/.julia/environments/v1.8", "_=/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia", "USER=jeff", "TERM=xterm-256color", "HOME=/Users/jeff", "TERM_PROGRAM_VERSION=433"]), ProcessExited(2)) [2]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:542 [inlined]
  [2] open(::Tar.var"#83#86"{Base.DevNull, Bool, Tar.var"#1#2", String}, ::Cmd; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./process.jl:417
  [3] open(::Function, ::Cmd)
    @ Base ./process.jl:404
  [4] arg_read
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/ArgTools/src/ArgTools.jl:75 [inlined]
  [5] extract(predicate::Function, tarball::Cmd, dir::String; skeleton::Nothing, copy_symlinks::Nothing, set_permissions::Bool)
    @ Tar /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Tar/src/Tar.jl:231
  [6] #extract#89
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Tar/src/Tar.jl:255 [inlined]
  [7] unpack(tarball_path::String, dest::String; verbose::Bool)
    @ Pkg.PlatformEngines /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/PlatformEngines.jl:385
  [8] install_archive(urls::Vector{Pair{String, Bool}}, hash::Base.SHA1, version_path::String; io::Base.TTY)
    @ Pkg.Operations /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:514
  [9] macro expansion
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:727 [inlined]
 [10] (::Pkg.Operations.var"#46#51"{Bool, Pkg.Types.Context, Tuple{SubString{String}, Dict{Base.UUID, Base.SHA1}}, Channel{Any}, Channel{NamedTuple{(:pkg, :urls, :path), Tuple{Pkg.Types.PackageEntry, Set{String}, String}}}})()
    @ Pkg.Operations ./task.jl:476
```

It works fine on the previous version of graphite2_jll (1.3.13).

Here's my info:
```
julia> versioninfo()
Julia Version 1.8.0-DEV.1437
Commit a0093d2ffb (2022-02-01 00:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, haswell)
```

**Comment by giordano** [comment] 2022-02-03 00:12
This might be an issue on the julia side, although `Graphite2_jll` [hasn't been touched since last May](](https://github.com/JuliaBinaryWrappers/Graphite2_jll.jl/commit/3b08421c6201219f26c6bbe410a2b64dd7a92634), and `p7zip_jll` was last updated in Julia [February last year](https://github.com/JuliaLang/julia/pull/39805), so nothing of this changed recently at all.  For what is worth, I can't reproduce on an M1 macbook using a nightly build of julia for x86_64-apple-darwin

**Comment by IanButterworth** [comment] 2022-02-03 00:17
I saw this yesterday too https://github.com/tro3/ThreadPools.jl/runs/5027387410?check_suite_focus=true#step:4:56

Very weird.

**Comment by jdeldre** [comment] 2022-02-03 00:20
Thanks for checking. I've re-quoted my information below (Intel Macbook with x86_64-apple-darwin).
```
julia> versioninfo()
Julia Version 1.8.0-DEV.1437
Commit a0093d2ffb (2022-02-01 00:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, haswell)
```

**Comment by giordano** [comment] 2022-02-03 00:25
When you get the error, is the file still there or it had been cleaned up already?

**Comment by jdeldre** [comment] 2022-02-03 00:29
Thanks for checking. I've re-quoted my information below (Intel Macbook with x86_64-apple-darwin). Also, as noted, it's definitely associated with something in the latest version of graphite itself or the Graphite2_jll artifact built from it, since it works fine with the previous version on my system.

On error, the temp file is still there, but empty.

```
julia> versioninfo()
Julia Version 1.8.0-DEV.1437
Commit a0093d2ffb (2022-02-01 00:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.0 (ORCJIT, haswell)
```

**Comment by giordano** [comment] 2022-02-03 00:32
> On error, the temp file is still there, but empty.

@staticfloat can you please check there is something wrong in the PkgServer cache (maybe US)?

**Comment by staticfloat** [comment] 2022-02-03 00:34
@jdeldre what does the following show for you?

```
$ curl -L https://pkg.julialang.org/meta
{"start_time":"2022-02-02T06:25:17.792","pkgserver_version":"0.2.0-5742db3844876dcbca176331727e0e9adf3595e8","pkgserver_url":"https://us-west2.pkg.julialang.org","julia_version":"1.7.1","live_tasks":"11","registry_watchdog_task":"started","last_registry_update":"2022-02-03T00:34:41.459","registry_update_task":"started","maxrss":406523904}
```

**Comment by jdeldre** [comment] 2022-02-03 01:28
@staticfloat Here it is

```
% curl -L https://pkg.julialang.org/meta
{"start_time":"2022-02-02T06:25:17.792","pkgserver_version":"0.2.0-5742db3844876dcbca176331727e0e9adf3595e8","pkgserver_url":"https://us-west2.pkg.julialang.org","julia_version":"1.7.1","live_tasks":"11","registry_watchdog_task":"started","last_registry_update":"2022-02-03T01:27:28.588","registry_update_task":"started","maxrss":406523904}% 
```

**Comment by giordano** [comment] 2022-02-04 16:52
@jdeldre on Slack it was reported that setting the environment variable `JULIA_PKG_SERVER="eu-central.pkg.julialang.org"` solves the issue (I'm in Europe and don't have problems).  Now, I do _**not**_ recommend going around redirecting all the PkgServer traffic to Europe (it wouldn't do anything good, besides clogging up an unrelated region), that may be a good local _**temporary**_ solution until the issue is actually fixed in the PkgServer.  CC: @staticfloat.

**Comment by jdeldre** [comment] 2022-02-04 16:59
@giordano Thanks for the tip! That does indeed fix it for now.

**Comment by giordano** [comment] 2022-02-04 17:17
BTW, I've got a reproducer:
```
JULIA_PKG_SERVER="us-west2.pkg.julialang.org" JULIA_DEPOT_PATH=$(mktemp -d)  -e 'using Pkg; Pkg.add("Graphite2_jll")'
```
Requires Julia v1.8

**Comment by giordano** [comment] 2022-02-04 17:26
Running the above code with Julia v1.7 I get:
```
% JULIA_PKG_SERVER="us-west2.pkg.julialang.org" JULIA_DEPOT_PATH=$(mktemp -d) julia -e 'using Pkg; Pkg.add("Graphite2_jll")' 
  Installing known registries into `/tmp/tmp.pI2ePKfqs2`
    Updating registry at `/tmp/tmp.pI2ePKfqs2/registries/General.toml`
   Resolving package versions...
ERROR: /tmp/jl_oHWDG2gp6614
Can not open the file as archive

┌ Warning: failed to extract archive downloaded from https://us-west2.pkg.julialang.org/package/3b182d85-2403-5c21-9c21-1e1f0cc25472/344bf40dcab1073aca04aa0df4fb092f920e4011
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:497
   Installed Preferences ─── v1.2.3
   Installed JLLWrappers ─── v1.4.1
   Installed Graphite2_jll ─ v1.3.14+0
  Downloaded artifact: Graphite2
    Updating `/tmp/tmp.pI2ePKfqs2/environments/v1.7/Project.toml`
  [3b182d85] + Graphite2_jll v1.3.14+0
    Updating `/tmp/tmp.pI2ePKfqs2/environments/v1.7/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.4.1
  [21216c6a] + Preferences v1.2.3
  [3b182d85] + Graphite2_jll v1.3.14+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
Precompiling project...
  6 dependencies successfully precompiled in 2 seconds
```
The first download attempts fails, the fallback is successful.

@staticfloat we've got the faulty file: https://us-west2.pkg.julialang.org/package/3b182d85-2403-5c21-9c21-1e1f0cc25472/344bf40dcab1073aca04aa0df4fb092f920e4011 is empty, https://eu-central.pkg.julialang.org/package/3b182d85-2403-5c21-9c21-1e1f0cc25472/344bf40dcab1073aca04aa0df4fb092f920e4011 isn't.

**Comment by giordano** [comment] 2022-02-04 17:29
Cached cleaned up and issue solved by @fredrikekre.  But still unclear why v1.8 doesn't go through the fallback download option.

**Closed by giordano** 2022-02-04 17:29 UTC
