### ISSUE TITLE
QT5 not working on Windows

### ISSUE THREAD

**Issue by ig-or** [JuliaPackaging/Yggdrasil#8418] opened 2024-04-02 21:42 UTC
```
ERROR: LoadError: InitError: could not load library "C:\Users\User\.julia\artifacts\9bf932c8791cfe70751ea60e728460268bf57777\bin\Qt53DAnimation.dll"
Access is denied.
```

I can see that the DLL files installed in the artifact does not have 100% correct permissions: user "Everyone" have only "Read", but IMHO there should be "read&execute".  

On Linux side, everything looks fine.

**Comment by giordano** [comment] 2024-04-02 21:43
Duplicate of https://github.com/JuliaLang/julia/issues/52272

**Closed by giordano** 2024-04-02 21:43 UTC
