### ISSUE TITLE
`using SDL2_jll` is slow

### ISSUE THREAD

**Issue by cmcaine** [JuliaPackaging/Yggdrasil#1050] opened 2020-05-19 03:11 UTC
`using SDL2_jll` takes 3-4 seconds on my machines, much longer than `using Libdl; dlopen("/usr/lib/libSDL2.so")` and I think the profiler is telling me that it's spending about a third of the time in typeinfer.jl/typeinf_ext and a third in Artifacts.jl/do_artifact_str

Is moderately slow loading a known issue or unexpected? Any suggestions for causes I could track down? Any suggestions for good ways to profile it?

Current ideas:

- time the load time for each of the dependencies of SDL2_jll
- there're lots of globals in the wrappers, maybe reduce that?

I've attached the profile the `@profiler using SDL2_jll` let me save, but I don't actually know how you load that ;)
[using_SDL2_jll.txt](https://github.com/JuliaPackaging/Yggdrasil/files/4648013/using_SDL2_jll.txt)

**Comment by fingolfin** [comment] 2020-05-19 10:21
I think to process this, more information might be needed... E.g. What Julia version? What OS? What kind of machine (CPU speed? using an SSD? etc.).

For me, I see this:
```
julia> @time using SDL2_jll
  0.685539 seconds (838.89 k allocations: 45.794 MiB, 0.78% gc time)
```
Now 0.7 seconds still isn't great, but quite a bit faster than what you report (this was measure with Julia 1.4.1 on a MacBook Pro 2018 running macOS 10.14.6, with a fast SSD, a 2,6 GHz Intel Core i7).

Note that `SDL2_jll` has a ton of dependencies as one can see when installing it:
```
(@v1.4) pkg> add SDL2_jll
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed Xorg_libXfixes_jll ──────── v5.0.3+2
  Installed SDL2_jll ────────────────── v2.0.12+0
  Installed Xorg_libXcursor_jll ─────── v1.2.0+2
  Installed Xorg_libXau_jll ─────────── v1.0.9+2
  Installed Xorg_libXScrnSaver_jll ──── v1.2.3+2
  Installed XSLT_jll ────────────────── v1.1.33+2
  Installed Xorg_libxcb_jll ─────────── v1.13.0+2
  Installed Libgpg_error_jll ────────── v1.36.0+1
  Installed Xorg_libXdmcp_jll ───────── v1.1.3+2
  Installed Libglvnd_jll ────────────── v1.3.0+1
  Installed Xorg_libXrender_jll ─────── v0.9.10+2
  Installed Xorg_libpthread_stubs_jll ─ v0.1.0+1
  Installed Xorg_libXext_jll ────────── v1.3.4+2
  Installed Xorg_libXinerama_jll ────── v1.1.4+2
  Installed Xorg_libX11_jll ─────────── v1.6.9+2
  Installed Libgcrypt_jll ───────────── v1.8.5+1
  Installed Xorg_libXrandr_jll ──────── v1.5.2+2
  Installed Xorg_xtrans_jll ─────────── v1.4.0+1
```

When you do `using SDL2_jll`, all of those are loaded (see also https://github.com/JuliaBinaryWrappers/SDL2_jll.jl/blob/master/Project.toml). Each of them takes a little bit of time, to compile the precompiled julia bytecode into machine code. It's not much, but it adds up.

This is a general problem in Julia, I am afraid. I am also sure the clever Julia devs are working hard on improving this, but it's difficult. It's a variant of the classic conflict between improving throughput and latency: for now, Julia aims to produce great machine code, which results in great throughput when you run the code a lot, but increases latency (= the time taken to load the code). The same problem has been encountered by other JIT system in the past. For example, browser vendors use all kinds of tricks to make Javascript code execute "fast" (as in: start quickly, low latency) and also "fast" (as in: runs quickly , high throughput). One trick some of them employed at some point in time or another (this keeps changing) is to have two different compilation systems: one which has low latency but produces code that's not super optimized; and one with higher latency but which produces better code. Then profiling is used to decided when to use which "compiler". I imagine that Julia may need to introduce such a system at some point: it's pointless to optimize the code in the JLLs very much.

But compilation speed is not the only thing, of course; just looking up and loading all these files takes some time; and if you have a slower disk drive, it hits you particularly hard.  This in turn could be improved by reducing the number of dependencies in SDL2_jll (on macOS, for example, all those `Xorg` deps should just not be there: one will want to use the native macOS support in SDL2 only. Same on Windows. Only on Linux/FreeBSD does this make sense. But unfortunately, dependencies of a JLL are all or nothing; AFAIK you can't say something is a dependency only on some platforms, not others).

Anyway, so all in all, I consider this performance "normal" right now; mind you, I am not saying it is good or shouldn't be improved, just that SDL2_jll is not particularly slow to load for me compared to other things.

**Comment by giordano** [comment] 2020-05-19 10:27
Note that this isn't specific to `SDL2_jll` but to all JLL packages.  The main issue is that the `__init__` functions of the JLL packages are slowish, and despite being all pretty much the same they are recompiled all the times.  [This package](https://github.com/giordano/TestGtkMegaJLL.jl) that merges the content of many JLL packages in a single place with a single `__init__` function is faster to load.

There is more discussion at https://github.com/JuliaGraphics/Gtk.jl/issues/466, as this issue very badly affects `Gtk.jl`.  Spoiler: situation in Julia v1.5 should slightly improve.

**Comment by giordano** [comment] 2020-05-19 10:44
> Spoiler: situation in Julia v1.5 should slightly improve.

```julia
julia> @time using SDL2_jll
  2.711368 seconds (3.19 M allocations: 168.207 MiB, 3.11% gc time)

julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_PKG_SERVER = https://geo.pkg.julialang.org
```
and
```julia
julia> @time using SDL2_jll
  1.789793 seconds (1.57 M allocations: 96.061 MiB, 0.51% gc time)

julia> versioninfo()
Julia Version 1.5.0-DEV.865
Commit 097f0b0c86 (2020-05-06 12:56 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
Environment:
  JULIA_PKG_SERVER = https://geo.pkg.julialang.org
```

**Comment by cmcaine** [comment] 2020-05-19 11:38
Thanks @fingolfin, but I actually knew pretty much all of that already :) I should have included versioninfo on the two machines I tested on, though.

Thanks @giordano, that's a really useful issue! The __init__ methods look pretty similar across different wrappers. Perhaps we can do something like this for the ones that don't need custom code? Then the body of Utils/init could be precompiled.

```jl
# BinaryWrapperUtils.jl/src/wrappers/x86_64-linux-gnu.jl

function init(artifact_dir, PATH_lists, LIBPATH_lists)
    ...
    return path, handle, PATH_list, LIBPATH_list, PATH, LIBPATH
end
```

```jl
# SDL2_jll.jl/src/wrappers/x86_64-linux-gnu.jl

using BinaryWrapperUtils.x86_64_linux_gnu: init

const ...

# I wonder if this can be done in precompile? It shouldn't change, should it?
const artifact_dir = artifact"SDL2"

function __init__()
    global libsdl2_path, libsdl2_handle, PATH_list, LIBPATH_list, PATH, LIBPATH = init(...)
end
```

**Comment by cmcaine** [comment] 2020-05-19 11:46
> This in turn could be improved by reducing the number of dependencies in SDL2_jll (on macOS, for example, all those Xorg deps should just not be there: one will want to use the native macOS support in SDL2 only.

I think this is doable? The `using Xorg...` lines could just be removed from the wrappers on systems that don't need that. Pkg will still download the _jll package, but if we never execute the `artifact"blah"` bit, then the binaries won't even be downloaded.

**Comment by giordano** [comment] 2020-05-19 11:56
If an artifact is not available for a given platform, the package stops here: https://github.com/JuliaBinaryWrappers/Xorg_libX11_jll.jl/blob/70597bb442e7ee846662597955c59e58578b99cc/src/Xorg_libX11_jll.jl#L43-L45.  In this case no wrapper is included, because there is no wrapper, the package is basically no-op.  The `__init__` functions are defined only in the wrappers.

**Comment by giordano** [comment] 2020-05-19 12:11
And regarding your suggestion about how to reorganise the init function, unfortunately most of the time is spent in the `artifact"..."` string macro :sweat_smile:  Optimising the rest doesn't help much.

>     # I wonder if this can be done in precompile? It shouldn't change, should it?

It actually can: an artifact can be deleted by `]gc` for example.  So we really need to make sure that the artifact is still there at runtime.  Also, one can move the Julia depot.

**Comment by fingolfin** [comment] 2020-05-19 13:42
@cmcaine agreed that "this is doable" (removing `using Xorg` on platforms not needing it), it still needs somebody to do it. There are lots of "simple" improvements possible to BinaryBuilder, BinaryProvider, Yggdrasil, Julia itself, ... that just "somebody" has to implement :-)

**Comment by giordano** [comment] 2020-05-19 13:55
> (removing using Xorg on platforms not needing it)

As I explained above, this is useless and gives no speedup in practice.

The problem is the `artifact"..."` string macro being recompiled all the time.  [`TestGtkMegaJLL.jl`](https://github.com/giordano/TestGtkMegaJLL.jl) is superfast, on my machine it takes 0.4 seconds to load, while `GTK3_jll` takes more than 10 times more than that.  If someone wants to take an action, should understand what's wrong with [`artifact"..."`](https://julialang.github.io/Pkg.jl/v1/api/#Pkg.Artifacts.@artifact_str).  Invalidation seems to play an important role here, as Tim Holy's work on it gave a sensible boost (see https://github.com/JuliaLang/Pkg.jl/pull/1806 and https://github.com/JuliaLang/Pkg.jl/pull/1807).

**Comment by fingolfin** [comment] 2020-05-19 14:38
@giordano yes, I understood that. My point was more to the general (it's always easy to say something is doable; it may even be true; but somebody still needs to do it!), not the specific. But thanks for pointing out once again that this specific change won't help.

**Comment by cmcaine** [comment] 2020-05-19 14:40
@giordano I've been playing with that today. I saved about 1 second by fiddling with precompiles, then realised that that was more or less fixed in v1.5 or 1.6 ;)

Now I'm setting up a profiling environment on v1.6 to see if I can make any more improvements, but probably I'll have to take a break for some other work!

**Comment by cmcaine** [comment] 2020-05-19 19:34
I've seen substantial time spent in `artifact_meta` and `ensure_artifact_installed`, so I'm not sure it's all invalidation, at least for my use case. By precalculating artifact_meta, I can get the time down by another .4s, I'd need to add a dependency on every file in `artifact_dirs("Override.toml")`, but I think that's okay (typically only one file).

I've learnt a bunch by looking into this, but I'm going to leave it for now - it's a bit too tricky to develop Pkg (I think I have to build Julia each time I want to do a proper benchmark), and the potential win is too small for me.

**Comment by staticfloat** [comment] 2020-05-23 03:03
Rest assured @cmcaine, this will improve in the future.  We have a plan, including moving elements of the Artifacts code into Base that is slowly coming together,  I'm not sure it will make it into 1.6, but we intend for JLL package load times to improve significantly in the future.

**Comment by PallHaraldsson** [comment] 2020-08-09 21:32
>using SDL2_jll takes 3-4 seconds on my machines

I get:
```
$ ~/julia-1.6-latest-dffc8895b8/bin/julia -O0 -q
julia> @time using SDL2_jll
  1.453293 seconds (2.21 M allocations: 141.087 MiB, 2.57% gc time)

slightly better than on default settings:

julia> @time using SDL2_jll
  1.742618 seconds (2.21 M allocations: 141.085 MiB, 2.13% gc time)
```

If you generate new SDL2_jll then you get this slight improvement as a default (my PR in effect adds -O0).

FYI, seemingly sa I have musl version of Julia 1.5:

```
julia> @time using SDL2_jll
[ Info: Precompiling SDL2_jll [ab825dc5-c88e-5901-9575-1e5e20358fcf]
ERROR: LoadError: LoadError: InitError: could not load library "/home/pharaldsson_sym/.julia/artifacts/d3fdedb2fb04ce1501dc94c7aa37d497f441bf50/lib/libgcrypt.so"
Error loading shared library libgpg-error.so.0: No such file or directory (needed by /home/pharaldsson_sym/.julia/artifacts/d3fdedb2fb04ce1501dc94c7aa37d497f441bf50/lib/libgcrypt.so)
Stacktrace:
 [1] #dlopen#3 at /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
 [2] dlopen at /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
 [3] __init__() at /home/pharaldsson_sym/.julia/packages/Libgcrypt_jll/lfPdk/src/wrappers/x86_64-linux-musl.jl:43
 [4] _include_from_serialized at ./loading.jl:697
 [5] _require_search_from_serialized at ./loading.jl:782
 [6] _require at ./loading.jl:1007
 [7] require at ./loading.jl:928
 [8] require at ./loading.jl:923
 [9] include at ./Base.jl:380
 [10] include at ./Base.jl:368 [inlined]
 [11] include(::String) at /home/pharaldsson_sym/.julia/packages/XSLT_jll/aqo3w/src/XSLT_jll.jl:1
 [12] top-level scope at /home/pharaldsson_sym/.julia/packages/XSLT_jll/aqo3w/src/XSLT_jll.jl:50
 [13] include at ./Base.jl:380
 [14] include at ./Base.jl:368
 [15] top-level scope at none:2
 [16] eval at ./boot.jl:331 [inlined]
 [17] eval(::Expr) at ./client.jl:467
 [18] top-level scope at ./none:3
during initialization of module Libgcrypt_jll
in expression starting at /home/pharaldsson_sym/.julia/packages/XSLT_jll/aqo3w/src/wrappers/x86_64-linux-musl.jl:4
in expression starting at /home/pharaldsson_sym/.julia/packages/XSLT_jll/aqo3w/src/XSLT_jll.jl:43
ERROR: LoadError: LoadError: Failed to precompile XSLT_jll [aed1982a-8fda-507f-9586-7b0439959a61] to /home/pharaldsson_sym/.julia/compiled/v1.5/XSLT_jll/HNSqD_glT1O.ji.
Stacktrace:
 [1] error at ./error.jl:33
[..]
```

**Comment by staticfloat** [comment] 2020-09-28 20:28
Update; it will make it into 1.6, 95% of the work has landed, and in the next few days we're going to be regenerating a lot of JLLs to give slightly faster JLLs on 1.3-1.5, and significantly faster JLLs on 1.6+.

**Comment by giordano** [comment] 2020-09-28 20:37
And "significantly faster JLLs on 1.6+" means something of the order of ~0.04 seconds (or maybe less, on machines faster than my 5-year old laptop)

**Comment by giordano** [comment] 2020-10-16 23:25
Not all packages in the stack of `SDL2_jll` have been updated yet, but we're getting there.  For the time being, with the latest version of the registry:
```
% for jl in julia-13 julia-14 julia julia-master; do ${jl} --project=. --startup-file=no -e '@time using SDL2_jll'; done
  2.758919 seconds (2.80 M allocations: 151.012 MiB, 0.17% gc time)
  2.508335 seconds (2.38 M allocations: 131.082 MiB, 0.47% gc time)
  1.482902 seconds (1.48 M allocations: 92.384 MiB, 0.39% gc time)
  0.183393 seconds (166.13 k allocations: 12.646 MiB, 42.75% compilation time)
```
I think this issue can be closed now.

**Closed by giordano** 2020-10-16 23:25 UTC
