### ISSUE TITLE
C++ shared pointers to arrays don't compile

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#5851] opened 2022-11-12 03:32 UTC
This C++ code
```C++
#include <memory>
std::shared_ptr<double[]> f(double *p) { return std::shared_ptr<double[]>(p); }
```
is legal C++17. It creates a shared pointer to an array. Clang 13.0.1 on Godbolt.org accepts it as well.

Unfortunately, the compilers e.g. for `x86_64-unknown-freebsd-julia_version+1.8.0-mpi+mpich` do not accept this code. I assume that the C++ compiler itself there is fresh enough, but the stdlibc++ (and its `<memory>`) there is too old to support this feature. Even a `preferred_gcc_version=v"11"` does not help.

How do I get a more recent C++ standard library?

[This](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=23602&view=logs&j=f2e6ceac-aa24-5772-0b29-212e71ee4690&t=913e413f-d6ee-53f3-cf4e-4b2618d134a2&l=37876) shows the error message in CI. I think both Apple and FreeBSD have the same problem.

**Comment by giordano** [comment] 2022-11-18 16:49
For FreeBSD we use version 12.2 https://github.com/JuliaPackaging/Yggdrasil/blob/be81379b7bd9c48c26fba7516d61e7a5fdce6b59/0_RootFS/PlatformSupport/build_tarballs.jl#L54 which should be about 2-year old, according to http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/old-releases/i386/12.2-RELEASE/.  Is it really that old?

**Comment by eschnett** [comment] 2022-11-18 19:07
FreeBSD 12 is from 2018. I assume that FreeBSD 12.x would not update major versions of packages without need, and thus even FreeBSD 12.3 would be stuck with a 2018 LLVM.

**Comment by giordano** [comment] 2022-11-18 19:09
CC @ararslan

**Comment by ararslan** [comment] 2022-11-18 19:41
Right, AFAIK FreeBSD doesn't update the version of LLVM used for the base system in minor releases, so the system C++ standard library will be tied to that version. It's possible to install a newer LLVM on FreeBSD 12 from the package manager but that's installed separately from the system version.

**Comment by eschnett** [comment] 2022-11-18 19:43
We need to be careful, even if we install a newer LLVM, then its compiler might be configured to use the system libc++ for compatibility. (Otherwise, using an existing system library might fail.)

**Comment by giordano** [comment] 2022-11-18 19:48
I think this is ultimately a duplicate of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/863.  We'd need a mechanism to easily switch libc/SDK, and declare compatibility

**Comment by eschnett** [comment] 2022-11-18 20:41
On what time scale could this be remedied? This is at the moment a stopper for https://github.com/JuliaPackaging/Yggdrasil/pull/5850. If this is a non-trivial task, then I need to decide whether to stay with the current version, disable some of the architectures, or add a patch as work-around (if possible).

**Comment by giordano** [comment] 2022-11-18 21:56
You can ask the 25% of Julia users on freebsd, already contributing to the discussion, if they're OK with not supporting freebsd for this package for the time being

**Comment by eschnett** [comment] 2022-11-18 22:15
... and what about MacOS??? (Probably same problem there.)

**Comment by giordano** [comment] 2022-11-18 22:18
Macos is the only platform for which we can "easily" swap out the sdk. What version do you need?

**Comment by eschnett** [comment] 2022-11-18 23:16
I will have to experiment. I assume that's as easy as it looks, just replacing the download url. Will let you know.

**Comment by eschnett** [comment] 2022-11-21 01:21
As it turns out, the MacOS SDK does not contain the C++ compiler, nor its header files. Thus updating it does not help.

The C++ header files should be distributed with Xcode. Can we download and install Xcode as well? Do you know how to do so in the MacOS build container? Xcode is e.g. available here: https://xcodereleases.com .

**Comment by giordano** [comment] 2022-11-21 18:36
At the moment we provide LLVM up to v13.  Would that feature require LLVM 14?

**Closed** 2022-11-21 19:41 UTC

**Comment by eschnett** [comment] 2022-11-21 20:07
Are we using our own libc++, or are we using the System libc++ on Darwin? I thought the latter. In this case the version of LLVM (which provides clang++) isn't relevant.

I check on my macOS laptop, and even the newest (beta) version of Xcode does not support this C++17 feature. It seems that Apple's libc++ simply doesn't implement it. Maybe they are using their own fork of LLVM and missed that feature?

In the case of openPMD_api, the source code actually contains a work-around for older versions of LLVM. I am now enabling this work-around unconditionally. The cost is small, it's using an explicit destructor for a shared pointer.

**Comment by giordano** [comment] 2022-11-21 21:29
libc++ is only needed for linking.  In the build environment it comes from the SDK, but for example on macOS we simply have the stub tbd files.  The header files used to compile come from the compiler shard, they're separate from libc++.  I don't think you elaborated on what "compilers [...] do not accept this code" concretely means.

**Comment by eschnett** [comment] 2022-11-21 21:40
The code calls the constructor `std::shared<int[]>(int*)`. That is, it converts a regular `int *` to a "shared pointer to an int array". See e.g. https://godbolt.org/z/5K1dz5Kxb for an example.

The latter – shared pointers to C-style arrays – are new in C++17. This constructor is supposed to be provided by `<memory>`, but it apparently isn't for Apple's C++ compiler. On my macOS system, GCC accepts this code, but the System C++ compiler (Apple's LLVM derivative) does not. Clang 15 (installed via MacPorts) also rejects this code, although it seems to use its own libc++. Clang 15 on Godbolt accepts this code, but I think this Clang uses a GCC libstdc++, judging from the include paths.

**Comment by giordano** [comment] 2022-11-21 21:49
Yes, on Linux and Windows we link to libstdc++: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/475288378ad6aa99bb3eeffe7ec67b4c1505e29a/src/Runner.jl#L329-L333 I think that's the norm on Linux systems which use gcc by default.  But the `memory` header file comes from LLVM:
```console
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("x86_64", "macos"))'
sandbox:${WORKSPACE} # echo '#include <memory>' | clang -x c++ - -M | grep memory
  /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/include/c++/v1/memory \
sandbox:${WORKSPACE} # 
logout
% julia --compile=min -e 'using BinaryBuilderBase; BinaryBuilderBase.runshell(Platform("x86_64", "linux"))'
sandbox:${WORKSPACE} # echo '#include <memory>' | clang -x c++ - -M | grep memory
-.o: /opt/x86_64-linux-musl/bin/../include/c++/v1/memory \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/addressof.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/allocator_arg_t.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/uses_allocator.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/allocation_guard.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/allocator_traits.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/construct_at.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/pointer_traits.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/allocator.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/compressed_pair.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/pointer_safety.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/raw_storage_iterator.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/shared_ptr.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/unique_ptr.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/auto_ptr.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/temporary_buffer.h \
  /opt/x86_64-linux-musl/bin/../include/c++/v1/__memory/uninitialized_algorithms.h
```

**Comment by Downsite** [comment] 2023-07-31 07:54
@eschnett I am currently also running into this problem.
I see that the issue was closed.
Was there a solution found?
