### ISSUE TITLE
Cairo_jll v1.18 broke Cairo

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPackaging/Yggdrasil#7508] opened 2023-10-09 04:14 UTC
https://github.com/JuliaPackaging/Yggdrasil/pull/7454 updated `Cairo_jll` from v1.16 to v1.18.  This is on Windows, Julia v1.10.0-beta3.

```
]activate --temp
]add Cairo, Cairo_jll
st
```
outputs
``` 
Status `C:\Users\jaakkor2\AppData\Local\Temp\jl_6LQvIe\Project.toml`
  [159f3aea] Cairo v1.0.5
  [83423d85] Cairo_jll v1.18.0+0
```
Then `using Cairo` gives
```
julia> using Cairo
Precompiling Cairo
        Info Given Cairo was explicitly requested, output will be shown live
ERROR: LoadError: InitError: could not load library "C:\Users\jaakkor2\.julia\artifacts\56b50e15c4bf17d87081795ed94c739d3a24271c\bin\libpangocairo-1.0-0.dll"
The specified procedure could not be found.
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl .\libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl .\libdl.jl:116
  [3] macro expansion
    @ Pango_jll C:\Users\jaakkor2\.julia\packages\JLLWrappers\pG9bm\src\products\library_generators.jl:63 [inlined]
  [4] __init__()
    @ Pango_jll C:\Users\jaakkor2\.julia\packages\Pango_jll\PADSE\src\wrappers\x86_64-w64-mingw32.jl:22
  [5] run_module_init(mod::Module, i::Int64)
    @ Base .\loading.jl:1128
  [6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1116
  [7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base .\loading.jl:1061
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base .\loading.jl:1575
  [9] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1932
 [10] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1806
 [11] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [12] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [13] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1797
 [14] macro expansion
    @ Base .\loading.jl:1784 [inlined]
 [15] macro expansion
    @ Base .\lock.jl:267 [inlined]
 [16] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1747
 [17] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [18] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [19] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1740
 [20] include
    @ Base .\Base.jl:489 [inlined]
 [21] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base .\loading.jl:2216
 [22] top-level scope
    @ stdin:3
during initialization of module Pango_jll
in expression starting at C:\Users\jaakkor2\.julia\packages\Cairo\smWIA\src\Cairo.jl:1
in expression starting at stdin:3
  ✗ Cairo
  0 dependencies successfully precompiled in 1 seconds. 46 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Cairo [159f3aea-2a34-519c-b102-8c37f9878175]

Failed to precompile Cairo [159f3aea-2a34-519c-b102-8c37f9878175] to "C:\\Users\\jaakkor2\\.julia\\compiled\\v1.10\\Cairo\\jl_7422.tmp".
ERROR: LoadError: InitError: could not load library "C:\Users\jaakkor2\.julia\artifacts\56b50e15c4bf17d87081795ed94c739d3a24271c\bin\libpangocairo-1.0-0.dll"
The specified procedure could not be found.
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl .\libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl .\libdl.jl:116
  [3] macro expansion
    @ Pango_jll C:\Users\jaakkor2\.julia\packages\JLLWrappers\pG9bm\src\products\library_generators.jl:63 [inlined]
  [4] __init__()
    @ Pango_jll C:\Users\jaakkor2\.julia\packages\Pango_jll\PADSE\src\wrappers\x86_64-w64-mingw32.jl:22
  [5] run_module_init(mod::Module, i::Int64)
    @ Base .\loading.jl:1128
  [6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1116
  [7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base .\loading.jl:1061
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base .\loading.jl:1575
  [9] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1932
 [10] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1806
 [11] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [12] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [13] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1797
 [14] macro expansion
    @ Base .\loading.jl:1784 [inlined]
 [15] macro expansion
    @ Base .\lock.jl:267 [inlined]
 [16] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1747
 [17] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [18] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [19] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1740
 [20] include
    @ Base .\Base.jl:489 [inlined]
 [21] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base .\loading.jl:2216
 [22] top-level scope
    @ stdin:3
during initialization of module Pango_jll
in expression starting at C:\Users\jaakkor2\.julia\packages\Cairo\smWIA\src\Cairo.jl:1
in expression starting at stdin:
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\Users\jaakkor2\.julia\juliaup\julia-1.10.0-beta3+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Types.jl:70
  [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{…}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, timing::Bool, _from_loading::Bool, kwargs::@Kwargs{…})
    @ Pkg.API C:\Users\jaakkor2\.julia\juliaup\julia-1.10.0-beta3+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:1626
  [3] precompile(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::@Kwargs{_from_loading::Bool})
    @ Pkg.API C:\Users\jaakkor2\.julia\juliaup\julia-1.10.0-beta3+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:159
  [4] precompile
    @ Pkg.API C:\Users\jaakkor2\.julia\juliaup\julia-1.10.0-beta3+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:147 [inlined]
  [5] #precompile#114
    @ Pkg.API C:\Users\jaakkor2\.julia\juliaup\julia-1.10.0-beta3+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:146 [inlined]
  [6] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:1957
  [7] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1806
  [8] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
  [9] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [10] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:1797
 [11] macro expansion
    @ Base .\loading.jl:1784 [inlined]
 [12] macro expansion
    @ Base .\lock.jl:267 [inlined]
 [13] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1747
 [14] #invoke_in_world#3
    @ Base .\essentials.jl:921 [inlined]
 [15] invoke_in_world
    @ Base .\essentials.jl:918 [inlined]
 [16] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1740
Some type information was truncated. Use `show(err)` to see complete types.
```

Pinning Cairo  `]pin Cairo_jll@1.16` works.

CC: @jeremiahpslewis

**Comment by jeremiahpslewis** [comment] 2023-10-09 08:41
Thanks for reporting this issue. I just tried this on my M1 Mac and it works fine. I don't have access to a windows machine, but to narrow things down a bit more can you do the following and see if you get an error? It'd be great if you can also try it on the latest v1.9 version.

```julia
using Pkg
Pkg.activate(; temp=true)
Pkg.add("Pango_jll")
using Pango_jll
```

**Comment by jaakkor2** [comment] 2023-10-09 08:45
`Pango_jll` fails precompilation on both 1.9.3 and 1.10.0-beta3 erroring
```
ERROR: InitError: could not load library "C:\Users\jaakkor2\.julia\artifacts\56b50e15c4bf17d87081795ed94c739d3a24271c\bin\libpangocairo-1.0-0.dll"
```

**Comment by jeremiahpslewis** [comment] 2023-10-09 08:58
Ok, thanks. As a first step, I'd suggest we fix the version bounds on `Pango_jll` so that it depends on `Cairo_jll` v1.16. https://github.com/JuliaPackaging/Yggdrasil/pull/7511 Then I can try building the latest version of `Pango_jll` with `Cairo_jll` v1.18.

**Comment by giordano** [comment] 2023-10-09 09:03
I think it'd be better to yank the new version of Cairo in the registry (as I keep telling every single time, stuff has to be fixed in the registry first) for the time being until the problem is diagnosed. I don't see why our build pango is intrinsically incompatible with Cairo 1.18

**Comment by jeremiahpslewis** [comment] 2023-10-09 09:38
@jaakkor2 What happens when you do:

```julia
using Pkg
Pkg.activate(; temp=true)
Pkg.add("Cairo_jll")
using Cairo_jll
```

**Comment by jaakkor2** [comment] 2023-10-09 09:56
> ```julia
> using Pkg
> Pkg.activate(; temp=true)
> Pkg.add("Cairo_jll")
> using Cairo_jll
> ```

This works.

**Comment by jeremiahpslewis** [comment] 2023-10-09 10:19
Looks weird that it wants a `bin` path for a library...? `bin\libpangocairo-1.0-0.dll`

**Comment by jeremiahpslewis** [comment] 2023-10-12 10:47
@jaakkor2 Do you have any interest / ability to debug the windows issue? I'm at a total loss and don't have a PC.

**Comment by jaakkor2** [comment] 2023-10-12 11:13
I could have a look with [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon).  Were the versions yanked from registry, how to install that "bad" Pango_jll now?

**Comment by giordano** [comment] 2023-10-12 11:21
```
]add Pango_jll#main
```

**Comment by jaakkor2** [comment] 2023-10-12 21:12
This is where I ended with `Cairo_jll#main` (1.18.0+0), it is fine with Cairo_jll v1.16.1+1.
```
julia> dlopen("C:\\temp\\depo_cairo\\artifacts\\56b50e15c4bf17d87081795ed94c739d3a24271c\\bin\\libpangocairo-1.0-0.dll", 0x00000044)
ERROR: could not load library "C:\temp\depo_cairo\artifacts\56b50e15c4bf17d87081795ed94c739d3a24271c\bin\libpangocairo-1.0-0.dll"
The specified procedure could not be found.
Stacktrace:
 [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
   @ Base.Libc.Libdl .\libdl.jl:117
 [2] dlopen(s::String, flags::UInt32)
   @ Base.Libc.Libdl .\libdl.jl:116
 [3] top-level scope
   @ REPL[2]:1
```

Which procedure 🤷 I do not know what to try.  Procmon did not reveal anything to me.

> I can try building the latest version of Pango_jll with Cairo_jll v1.18.

That could be the next step? https://download.gnome.org/sources/pango/1.51/

**Comment by giordano** [comment] 2023-10-12 21:19
> Which procedure 🤷 I do not know what to try. 

Complain with the operating system withholding information from you (to be fair, also Linux has similarly bad error messages in this situation, but there are other tools to debug this kind of problems)

**Comment by jaakkor2** [comment] 2023-10-12 21:50
Ok, procmon to rescue.  On Windows, the system is trying to find
* libglib-2.0-0.dll
* libcairo-2.dll
* libgobject-2.0-0.dll

In directories
* C:\temp\depo_cairo\artifacts\56b50e15c4bf17d87081795ed94c739d3a24271c\bin      (=Pango_jll artifact)
* C:\Windows}System32
* C:\Windows\System
* C:\Windows
* C:\TEMP
* C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\Intel64_win\compiler
* C:\Windows\System32    (again!)
* ...

but not in the artifact directories of cairo and glib.

**Comment by giordano** [comment] 2023-10-12 21:56
_How_ are you using procmon?  Of course it doesn't know Julia had loaded libcairo already outside of any of those directories.

**Comment by jaakkor2** [comment] 2023-10-12 22:00
In procmon
* added a filter for process name contains julia
* start recording

In Julia
* `dlopen("C:\\temp\\depo_cairo\\artifacts\\56b50e15c4bf17d87081795ed94c739d3a24271c\\bin\\libpangocairo-1.0-0.dll", 0x00000044)`

In procmon
* stop recording
* look at the output

If one says simply `using Pango_jll`, output is too much to browse through.  Helps to run the specific erroring command.

**Comment by jaakkor2** [comment] 2023-10-12 22:36
Sorry for the confusion above. My procedure to debug was wrong.

**Comment by jaakkor2** [comment] 2023-10-16 07:38
#### Maybe a possible clue

`using Pango_jll` v1.50.14+0 and monitoring with procmon.

1)
With Cairo_jll v1.16.1+1 in the project, I see libraries loaded
* libpango-1.0-0.dll
* libpangocairo-1.0-0.dll
* libpangoft2-1.0-0.dll
* libpangowin32-1.0-0.dll
* DWrite.dll (first it tries to find it in artifact directory and failing, then `C:\Windows\System32\DWrite.dll` succeeding)

2)
With Cairo_jll#main v1.18.0+0 in the project, I see libraries loaded
* libpango-1.0-0.dll
* libpangocairo-1.0-0.dll
* libpangoft2-1.0-0.dll
* libpangowin32-1.0-0.dll
Then it starts to access `C:\Windows\System32\unregmp2.exe`, `C:\Windows\System32\en-US\KernelBase.dll.mui`, `.julia\juliaup\julia-1.9.3+0.x64.w64.mingw32\lib\julia\sys.dll`, `C:\Windows\System32\dbghelp.dll`, `.julia\juliaup\julia-1.9.3+0.x64.w64.mingw32\bin\libLLVM-14jl.dll`, ...

I would _guess_ problems loads libpangocairo could have something to do with `Dwrite.dll` that is Windows specific.

https://download.gnome.org/sources/pango/1.51/pango-1.51.0.news says
> build: Check for cairo DWrite dependency

#### About debugging on Windows

I did not yet read all the links carefully.

There is some discussion about debugging "specific procedure could not be found" here https://github.com/pact-foundation/pact-js/issues/1067.  FIrst omment links to https://github.com/Automattic/node-canvas/issues/1219#issuecomment-411288069 that says

> I think this can happen for a few reasons: (a) if you have another module that depends on one of the same dependencies of canvas, like cairo, (b) if you have multiple versions of canvas loaded by the same node.js process, sometimes, (c) if canvas was built with a different version of the dependencies than it's attempting to run with. When Windows searches for a DLL, if it finds one already loaded in memory with the same name, that one will be used even if it's the wrong one.

Well, Pango_jll v1.50.14+0 was compiled with earlier Cairo_jll than v1.18.0+0 .

Also for library debugging, GFlags is mentioned https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags.

**Comment by jeremiahpslewis** [comment] 2023-10-16 12:25
Based on [your link](https://download.gnome.org/sources/pango/1.51/pango-1.51.0.news), it would seem possible that pango `1.51` will handle `v1.18` Cairo better than the current `1.50` release does. Can we do something like pin pango `1.50` to Cairo `1.16`, and then unyank Cairo `1.18` and then build pango `1.51`?

**Comment by giordano** [comment] 2023-10-17 00:28
I think there's something broken in FreeType support for Pango (including version 1.51.0) on Windows with Cairo 1.18, or some combinations like that.  I have zero time to look further into this.

**Comment by jd-foster** [comment] 2023-10-19 01:23
(Copying over from Slack)
`DependenciesGUI.exe` tells me that these symbols, coming from libcairo-2.dll are the missing ones from the caller libpangocairo-1.0-0.dll:
![image](https://github.com/JuliaPackaging/Yggdrasil/assets/38274066/f5ae02dc-d305-4e6a-90b1-928ebd1d65c7)

They are [cairo_ft_font_options_substitute](https://www.cairographics.org/manual/cairo-FreeType-Fonts.html#cairo-ft-font-options-substitute) and [cairo_ft_font_face_create_for_pattern](https://www.cairographics.org/manual/cairo-FreeType-Fonts.html#cairo-ft-font-face-create-for-pattern) from the FreeType support within Cairo.

To reproduce this on a modern Windows installation, download the package from https://github.com/lucasg/Dependencies, unzip and run `DependenciesGui.exe`. 

Looking for the installation directory when doing `Pkg.add(Pkg.PackageSpec(name="Cairo_jll", rev="main"))`, open `...\.julia\packages\Cairo_jll\Hrnow\Artifacts.toml` and note the equivalent of
```
[[Cairo]]
arch = "x86_64"
git-tree-sha1 = "21565acae9e05502cb35f8d831289783d946a366"
os = "windows"
```
Do similarly for `Pango_jll` and open `...\.julia\artifacts\56b50e15c4bf17d87081795ed94c739d3a24271c\bin\libpangocairo-1.0-0.dll` in `DependenciesGui.exe`.

Now in `DependenciesGui.exe` under  Options > Customize search folders, open the SHA1-suffixed path of `libcairo-2.dll` found before: `C:\...\.julia\artifacts\21565acae9e05502cb35f8d831289783d946a366\bin\libcairo-2.dll`. Then you should see the graphic above.

(I tried using gflags but wasn't successful; I think the cross-compilation worklfow means that there isn't much for gflags to work with in the dlls)

**Closed** 2024-03-10 08:39 UTC
