### ISSUE TITLE
[GLFW] search path for radeonsi

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaPackaging/Yggdrasil#1721] opened 2020-10-01 04:02 UTC
I'm not sure whether this correct place for this issue, and I'm way out of my depth on this one. 

I'm wanting to use Makie.jl on an archlinux machine that has a radeon card. But I'm encountering an issue with GLFW during the Makie.jl build. 

```julia
(@v1.5) pkg> build GLMakie

...

   Building GLMakie ─→ `~/.julia/packages/GLMakie/4EXKe/deps/build.log`
┌ Error: Error building `GLMakie`: 
│ libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib/dri)
│ libGL error: failed to load driver: radeonsi
│ libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
│ libGL error: failed to load driver: swrast
│ init error of GLFW
│ ERROR: LoadError: OpenGL/GLFW wasn't installed correctly. This likely means,
│ you don't have an OpenGL capable Graphic Card,
│ you don't have the newest video driver installed,
│ or the GLFW build failed. If you're on linux and `]build` GLFW failed,
│ try manually adding `sudo apt-get install libglfw3` and then `]build GLMakie`.
│ If you're on a headless server, you still need to install x-server and
│ proper GPU drivers. You can take inspiration from this article
│ on how to get Makie running on a headless system:
│ https://nextjournal.com/sdanisch/makie-1.0
│ If you don't have a GPU, there is also a Cairo software backend
│ for Makie which you can use:
│ https://github.com/JuliaPlots/CairoMakie.jl.
│ Please check the below error and open an issue at:
│ https://github.com/JuliaPlots/GLMakie.jl.
│ After you fixed your OpenGL install, please run `]build GLMakie` again!
│ GLMakie will still load, but will be disabled as a default backend for Makie
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at /home/username/.julia/packages/GLMakie/4EXKe/deps/build.jl:63
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /home/username/.julia/packages/GLMakie/4EXKe/deps/build.jl:31
│ caused by [exception 1]
│ GLFWError (VERSION_UNAVAILABLE): GLX: Failed to create context: GLXBadFBConfig
│ Stacktrace:
│  [1] _ErrorCallbackWrapper(::Int32, ::Cstring) at /home/username/.julia/packages/GLFW/CBo9c/src/callback.jl:43
│  [2] CreateWindow(::Int64, ::Int64, ::String, ::GLFW.Monitor, ::GLFW.Window) at /home/username/.julia/packages/GLFW/CBo9c/src/glfw3.jl:499
│  [3] GLFW.Window(; name::String, resolution::Tuple{Int64,Int64}, debugging::Bool, major::Int64, minor::Int64, windowhints::Array{Tuple{UInt32,Int64},1}, contexthints::Array{Tuple{UInt32,Integer},1}, visible::Bool, focus::Bool, fullscreen::Bool, monitor::Nothing, share::GLFW.Window) at /home/username/.julia/packages/GLFW/CBo9c/src/glfw3.jl:344
│  [4] top-level scope at /home/username/.julia/packages/GLMakie/4EXKe/deps/build.jl:34
│  [5] include(::String) at ./client.jl:457
│  [6] top-level scope at none:5
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949

```

```bash
ls -l /usr/lib/dri
-rwxr-xr-x  5 root root 13755160 Sep 17 20:59 i915_dri.so*
-rwxr-xr-x  5 root root 13755160 Sep 17 20:59 i965_dri.so*
-rwxr-xr-x  1 root root 35028896 Jul 19 00:54 iHD_drv_video.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 iris_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 kms_swrast_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 nouveau_dri.so*
-rwxr-xr-x  3 root root  9066920 Sep 17 20:59 nouveau_drv_video.so*
-rwxr-xr-x  5 root root 13755160 Sep 17 20:59 nouveau_vieux_dri.so*
-rwxr-xr-x  5 root root 13755160 Sep 17 20:59 r200_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 r300_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 r600_dri.so*
-rwxr-xr-x  3 root root  9066920 Sep 17 20:59 r600_drv_video.so*
-rwxr-xr-x  5 root root 13755160 Sep 17 20:59 radeon_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 radeonsi_dri.so*
-rwxr-xr-x  3 root root  9066920 Sep 17 20:59 radeonsi_drv_video.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 swrast_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 virtio_gpu_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 vmwgfx_dri.so*
-rwxr-xr-x 10 root root 21489808 Sep 17 20:59 zink_dri.so*
```

Being linux, I have mesa, the open-source implementation of the OpenGL specification.

**Comment by giordano** [comment] 2020-10-01 08:30
@SimonDanisch any clue?

**Comment by SimonDanisch** [comment] 2020-10-01 08:41
Seems to be the same as: https://github.com/JuliaGL/GLFW.jl/issues/198

**Comment by giordano** [comment] 2020-10-01 08:47
Right, same level of inscrutability :stuck_out_tongue:

**Comment by CiaranOMara** [comment] 2020-10-01 10:10
Let me know if there is anything I can do to help.

**Comment by giordano** [comment] 2020-10-03 16:12
I'm closing this issue, as it isn't related to packages built here: the problem is more with packages _not_ built here.  Also, there are already other tickets tracking the issue elsewhere, no need to keep open multiple ones.

**Closed by giordano** 2020-10-03 16:12 UTC

**Comment by SimonDanisch** [comment] 2020-10-03 20:50
> the problem is more with packages not built here.

Is that so? I thought this happens also with the BInaryBuilder version of GLFW ;) 
But I agree, this seems to be more of a Julia vs Driver issue..

**Comment by giordano** [comment] 2020-10-03 22:11
> Is that so?

Yes.  The problem is that a system library _not_ built with BinaryBuilder is being called.  That library has been compiled with a version of GCC more recent than the version of libstdc++ that comes with the official binary of Julia, hence the error.  How GLFW was built isn't relevant here.

**Comment by SimonDanisch** [comment] 2020-10-04 09:07
>the problem is more with packages not built here.

Ahh, you're talking about the driver :D that makes sense ;)
